### ISSUE TITLE
how to change it into java android ?

### ISSUE THREAD

**Issue by munawarul56** [edjacob25/Whatsapp-Analyzer-Android#1]
Because for the Kotlin version, I have difficulty running it.
I've tried the WhatsApp Analyzer version of Javafx yours, but I have trouble changing it to the Java Android version.

thanks
munawarul

**Comment by edjacob25** [comment]
I think at this point the JavaFX version and this version are quite different, I recommend you to use the android version as it is a lot more updated and it theoretically only requires you to install Android Studio and run the project.

I had already fixed some errors when building the app but I hadn't updated the code in here. You can use the latest version (at the time of this comment 900148f298b4be2de77bf1fb20ff28a55fffe06d) and build it. I tested it in my phone with Android 9 and it worked ok but I would like to hear about any problems you have with it, building and running it. 

Before you use it, you may probably want to change the logic in LineAnalyzer.kt to match the format in which your Whatsapp exports the file, this is mostly related to datetime formats and separators. It is set to match something like `31/12/2019 00:00 - Person1: Message`, but your phone may actually use something like `12-31-19 12:00 a. m. - Person1: Message` so you may want to adjust separators and date and time formats depending on that.

Hope this helps. cheers.
